name: build

permissions: read-all

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create'
        required: true
        default: 'v0.0.0'

# See https://github.com/cristalhq/.github/.github/workflows
jobs:
  # no build step, see e2e.yml

  codeql:
    permissions:
      security-events: write
    uses: cristalhq/.github/.github/workflows/codeql.yml@02d6a2a176fc4c22e5d84c2636f8a62e53dc17a4 # latest from main

  release:
    if: github.event_name == 'workflow_dispatch'
    uses: cristalhq/.github/.github/workflows/release.yml@02d6a2a176fc4c22e5d84c2636f8a62e53dc17a4 # latest from main
    permissions: 
      contents: write
    with:
      tag: ${{ github.event.input.tag }}
