name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # run "At 00:00 on Sunday"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create'
        required: true
        default: 'v0.0.0'


# See https://github.com/cristalhq/.github/.github/workflows
jobs:
  # TODO: disable for now
  build:
    uses: cristalhq/.github/.github/workflows/build.yml@cristaloleg-patch-1
    with:
      skipTests: true # e2e.yml is responsible for tests

  vuln:
    uses: cristalhq/.github/.github/workflows/vuln.yml@v0.2.1

  release:
    if: github.event_name == 'workflow_dispatch'
    uses: cristalhq/.github/.github/workflows/release.yml@v0.2.1
    with:
      tag: ${{ github.event.input.tag }}
