name: build

permissions: read-all

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create'
        required: true
        default: 'v0.0.0'

# See https://github.com/cristalhq/.github/.github/workflows
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    services:
      redis:
        image: redis:7.0-rc1-alpine3.15
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    uses: cristalhq/.github/.github/workflows/build.yml@454df049fccd7d81729b0c567b75662a2b77e97a # latest from main

  codeql:
    permissions:
      security-events: write
    uses: cristalhq/.github/.github/workflows/codeql.yml@454df049fccd7d81729b0c567b75662a2b77e97a # latest from main

  release:
    if: github.event_name == 'workflow_dispatch'
    uses: cristalhq/.github/.github/workflows/release.yml@454df049fccd7d81729b0c567b75662a2b77e97a # latest from main
    permissions: 
      contents: write
    with:
      tag: ${{ github.event.input.tag }}
