name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # run "At 00:00 on Sunday"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create'
        required: true
        default: 'v0.0.0'

# See https://github.com/cristalhq/.github/tree/main/.github/workflows
jobs:
  # TODO: disable for now
  build:
    uses: cristalhq/.github/.github/workflows/build.yml@v0.5.0
    with:
      skipTests: true # e2e.yml is responsible for tests

  vuln:
    uses: cristalhq/.github/.github/workflows/vuln.yml@v0.5.0
