name: e2e

permissions: read-all

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    services:
      redis:
        image: redis:7.0-rc1-alpine3.15
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # latest

      - name: Install Go
        uses: actions/setup-go@fcdc43634adb5f7ae75a9d7a9b9361790f7293e2 # latest
        with:
          go-version: 1.17

      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Mod
        run: go mod download

      - name: Go Generate
        run: go generate ./... && git diff --exit-code

      - name: Go Build
        run: go build -v ./...

      - name: Go Test
        run: go test -v ${{ inputs.race }} -shuffle=on -coverprofile=coverage.txt ./...
        env:
          TEST_REDIS_ADDR: ":6379"

      - name: Upload Coverage
        uses: codecov/codecov-action@81cd2dc8148241f03f5839d295e000b8f761e378 # v2.1.0
        continue-on-error: true
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
          fail_ci_if_error: false
