name: e2e

permissions: read-all

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        go: ['stable', 'oldstable']

    services:
      redis:
        image: redis:7.0.9-alpine3.17
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Check out code
        uses: actions/checkout@v3

      - name: Go Test
        run: go test -v -race -shuffle=on -coverprofile=coverage.txt ./...
        env:
          TEST_REDIS_ADDR: ":6379"

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        continue-on-error: true
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
          fail_ci_if_error: false
